Crowd_Funding/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('projects/', include('Projects.urls')),
    path('', include('Users.urls')),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='users/password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'
         ),
         name='password_reset_complete'),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Users/urls.py
from django.urls import path
from . import views
from django.conf.urls import url

app_name = "Users"
urlpatterns = [
    path('', views.home, name='home'),
    path('search/', views.search, name='search'),
    path('edit/', views.edit, name='edit'),
    path('delete/', views.delete, name='delete'),
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),

    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
]

Users/models.py
from django.db import models
from django.core.validators import RegexValidator
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="Users/images")
    birth_date = models.DateField(null=True, blank=True)
    phone = models.CharField(max_length=11, validators=[RegexValidator(regex='^01[0|1|2|5][0-9]{8}$',
                                            message="Phone number must be : 010 or 011 or 012 or 015.",
                                            code="Invalid Phone Number")])
    facebook_profile = models.URLField(null=True, blank=True)
    country = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return f'{self.user.username} Profile'

Users/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile
from django.forms import ModelForm, TextInput, ValidationError


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if email and User.objects.filter(email=email).count() > 0:
            raise ValidationError(u'This email address is already registered.')
        return email


class ProfileRegisterForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['phone', 'image']


class ProfileUpdate(ModelForm):
    class Meta:
        model = Profile
        fields = ['phone', 'birth_date','facebook_profile','country','image']
        widgets = {
            'birth_date': TextInput(attrs={'type': 'date'}),
        }


class UserRegisterFormUpdate(ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name']

Users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserRegisterForm, ProfileRegisterForm, UserRegisterFormUpdate, ProfileUpdate
from django.contrib.auth import login, authenticate
from Projects.models import Project, Category, Rate, Tag, Picture, FeatureProject
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .tokens import account_activation_token
from django.contrib.auth.models import User
from django.core.mail import EmailMessage
from django.http import HttpResponse


def register(request):
    if request.user.is_authenticated:
        messages.success(request, 'You are Already signed with account')
        return redirect('Users:home')

    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        profile_form = ProfileRegisterForm(request.POST, request.FILES)
        if form.is_valid() and profile_form.is_valid():
            user = form.save()
            user.refresh_from_db()
            user.is_active = False
            profile_form = ProfileRegisterForm(request.POST, request.FILES, instance=user.profile)
            user.save()
            profile_form.save()

            #######CONFIRMATION##########

            current_site = get_current_site(request)
            message = render_to_string('users/acc_active_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)).decode(),
                'token': account_activation_token.make_token(user),
            })
            mail_subject = 'Activate your KickPro account.'
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(mail_subject, message, to=[to_email])
            email.send()
            messages.success(request, 'Your account has been created But you have to Activate your account before '
                                      'Trying to login!')
            return redirect('Users:home')
            # username = form.cleaned_data.get('username')
            # raw_password = form.cleaned_data.get('password1')
            # user = authenticate(username=username, password=raw_password)
            # login(request, user)
            # messages.success(request, 'Your account has been created!')
            # return redirect('Users:home')
    else:
        form = UserRegisterForm()
        profile_form = ProfileRegisterForm()
    return render(request, 'users/register.html', {'form': form, 'profile': profile_form})


# Activation Function

def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist()):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        # profile.save()
        # registered = True
        login(request, user)

        messages.success(request, 'Thank you for your email confirmation. Now you can login your account.')
        return redirect('login')
        # return redirect('home')
    else:
        messages.success(request, 'Activation link is invalid or Expired!')
        return redirect('login')


@login_required
def profile(request):
    return render(request, 'users/profile.html')


def home(request):
    high_rate_pro = Rate.objects.all().order_by('-rate')[:6]
    images = Picture.objects.none()
    for rate in high_rate_pro:
        images = [x for x in images] + [y for y in rate.project.first_image()]
    latest_pro = FeatureProject.objects.all().order_by('-updated')[:5]
    categories = Category.objects.all()

    context = {'high_rate': high_rate_pro, 'latest_pro': latest_pro, 'cats': categories, 'images': images}
    return render(request, 'users/home.html', context)


@login_required
def search(request):
    search_key = request.GET.get('search', False)
    if search_key:
        search_key = request.GET['search']
        try:
            tag = Tag.objects.get(tag=search_key)
        except ObjectDoesNotExist:
            projects = Project.objects.none()
        else:
            projects = tag.project_set.all()

        title_pro = Project.objects.filter(title=search_key)
        records = (projects | title_pro).distinct()
        if not records:
            message = "Couldn't Find Any matching Project"
        else:
            message = "Search Results"
        context = {'message': message, 'records': records}
        return render(request, 'users/search.html', context)
    else:
        return redirect('Users:home')


@login_required
def edit(request):
    if request.method == 'POST':
        form = UserRegisterFormUpdate(request.POST, instance=request.user)
        profile_form1 = ProfileUpdate(request.POST, request.FILES, instance=request.user.profile)
        if form.is_valid() and profile_form1.is_valid():
            form.save()
            profile_form1.save()
            messages.success(request, 'Your account has been updated! ')
            return redirect('profile')

    else:
        form = UserRegisterFormUpdate(instance=request.user)
        profile_form1 = ProfileUpdate(instance=request.user.profile)

    return render(request, 'users/edit.html', {'form': form, 'profile': profile_form1})


@login_required
def delete(request):
    user = request.user
    user.delete()
    return redirect('logout')

Users/templates/users/acc_active_email.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,
http://{{ domain }}{% url 'Users:activate' uidb64=uid token=token %}
{% endautoescape %}

Users/templates/users/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'blog/main.css' %}">

</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url 'Users:home' %}">
                  <button class="btn btn-success my-2 my-sm-0">Crowd Funding</button>
              </a>
                {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'create_project' %}">
                    <button class="btn btn-success my-2 my-sm-0">Create New Project</button>
                </a>
                {% endif %}
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if user.is_authenticated %}
                <form class="form-inline" action="{% url 'Users:search' %}" method="get">
                    <input class="form-control mr-sm-2" type="text" name="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-success my-2 my-sm-0" type="submit">Search</button>
                </form>
                <a class="nav-item nav-link" href="{% url 'Users:profile' %}">
                    <button class="btn btn-success my-2 my-sm-0">Profile</button>
                </a>
                <a class="nav-item nav-link" href="{% url 'logout' %}">
                    <button class="btn btn-success my-2 my-sm-0">Logout</button>
                </a>
              {% else %}
                <a class="nav-item nav-link" href="{% url 'login' %}">
                    <button class="btn btn-success my-2 my-sm-0">Login</button>
                </a>
                <a class="nav-item nav-link" href="{% url 'Users:register' %}">
                    <button class="btn btn-success my-2 my-sm-0">Register</button>
                </a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-12">
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
          {% block content %}{% endblock %}
        </div>

      </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

Users/templates/users/edit.html
{% extends "users/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<style>
    .btn{
    padding: 10px;
    font-size: 15px;
    color: white;
    background: #5F9EA0;
    border: none;
    border-radius: 5px;

}
</style>
<script>

</script>

    <div class="content-section">

            <h3>my information</h3>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|crispy }}
                {{ profile|crispy }}
                <button type="submit" name="reg_user" class="btn">Update</button>


            </form>
        <br>
            <a class="btn" href="{% url 'Users:delete' %}" onclick="return confirm('Are you want to delete')">Delete Account</a>
</div>

        </div>
      </div>
    </div>
{% endblock content %}

Users/templates/users/home.html
{% extends "users/base.html" %}
{% block content %}
    <div class="alert alert-primary text-center" style="font-size:20px" role="alert">
              Highest Rated Projects
                <hr>
            <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
              <ol class="carousel-indicators">
                  {% for image in images %}
                        {% if forloop.counter == 1 %}
                            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                        {% else %}
                            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                        {% endif %}
                    {% endfor %}
              </ol>
              <div class="carousel-inner">
                   {% for image in images %}
                        {% if forloop.counter == 1 %}
                  <div class="carousel-item active">
                        {% else %}
                        <div class="carousel-item">
                        {% endif %}
                          <img src="{{ image.image.url }}" class="d-block w-100" height="350" alt="...">
                        <div class="carousel-caption d-none d-md-block">
                            <h5 style="color:white">{{ image.project.title }}</h5>
                            <p><a class="nav-item nav-link" href="{% url 'show_project' image.project.id %}">
                                <button class="btn btn-success my-2 my-sm-0">See More Details</button>
                            </a></p>
                        </div>
                   </div>
                    {% endfor %}
              </div>
              <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
              </a>
              <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
              </a>
            </div>
    </div>

    <div class="alert alert-primary text-center" style="font-size:20px" role="alert">
              Latest Featured Projects
                <hr>
            <div class="card-columns">
            {% for project in latest_pro %}
                <div class="card">
                    {% for image in project.project.first_image %}
                    <img class="card-img-top" src="{{ image.image.url }}" alt="Card image cap">
                    {% endfor %}
                    <div class="card-body">
                      <h5 class="card-title">{{ project.project.title }}</h5>
                      <p class="card-text">{{ project.project.details }}</p>
                         <p class="card-text">{{ project.updated }}</p>
                    </div>
                    <div class="card-footer">
                      <small class="text-muted"><a href="{% url 'show_project' project.project.id %}">See More</a></small>
                    </div>
                  </div>
            {% endfor %}
            </div>
    </div>

    <div class="alert alert-primary text-center" style="font-size:20px" role="alert">
        Categories
        <hr>
        {% for cat in cats %}
            <a href="{% url 'category' cat.id %}"><button type="button" class="btn btn-primary btn-lg">{{ cat.name }}
            </button></a>
        {% endfor %}
    </div>
{% endblock content %}

Users/templates/users/login.html
{% extends "users/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Login</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Need An Account? <a class="ml-2" href="{% url 'Users:register' %}">Sign Up Now</a>
            </small>
            <hr>
            <small class="text-muted">
                Forgot Your Password? <a class="ml-2" href="{% url 'password_reset' %}">Reset Your Passwrod</a>
            </small>
        </div>
    </div>
{% endblock content %}

Users/templates/users/logout.html
{% extends "users/base.html" %}
{% block content %}
    <h2>You have been logged out</h2>
    <div class="border-top pt-3">
        <small class="text-muted">
            <a href="{% url 'login' %}">Log In Again</a>
        </small>
    </div>
{% endblock content %}

Users/templates/users/password_reset.html
{% extends "users/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">reset password</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">request password reset</button>
            </div>
        </form>

    </div>
{% endblock content %}

Users/templates/users/password_reset_complete.html
{% extends "users/base.html" %}
{% block content %}
    <div class="alert alert-info">
        Your password has been set.
    </div>
    <a href="{% url 'login' %}">Sign In Here</a>
{% endblock content %}

Users/templates/users/password_reset_confirm.html
{% extends "users/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">reset password</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">reset password </button>
            </div>
        </form>

    </div>
{% endblock content %}

Users/templates/users/password_reset_done.html
{% extends "users/base.html" %}
{% block content %}
   <div class="alert alert-info">
       email has sent
   </div>
{% endblock content %}

Users/templates/users/profile.html
{% extends "users/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
        <div class="media-body">
            <div class="alert alert-primary text-center" style="font-size:20px" role="alert">
              {{ user.first_name }} {{ user.last_name }}
            </div>
          <p class="text-secondary">{{ user.email }}</p>
            <p class="text-secondary">Username : {{ user.username }}</p>
             <p class="text-secondary">{{ user.profile.phone }}</p>


            <div class="alert alert-primary text-center" style="font-size:20px" role="alert">
              My Projects
            </div>
            <hr>
            <table class="table table-dark">
                <tr>
                <th>title</th>
                <th>category</th>
                <th>total_target</th>
                <th>start_date</th>
                <th>end_date</th>
                <th>create_date</th>
                </tr>



                {% for m in user.project_set.all %}
            <tr>

                <td>{{ m.title }}</td>
                <td>{{ m.category }}</td>
                <td>{{ m.total_target }}</td>
                <td>{{ m.start_date }}</td>
                <td>{{ m.end_date }}</td>
                <td>{{ m.create_date }}</td>
                <td><a class="nav-item nav-link" href="{% url 'show_project' m.id %}">
                    <button class="btn btn-success my-2 my-sm-0">See Details</button>
                </a></td>

            </tr>

                  {% endfor %}
            </table>
            <hr>
            <div class="alert alert-primary text-center" style="font-size:20px" role="alert">
              My Donations
            </div>
            <table class="table table-dark">
                  <tr>
                <th>amount</th>
                <th>project</th>
                <th>user</th>
                <th>create_date</th>

                </tr>


            {% for m in user.donation_set.all %}
            <tr>
                <td>{{ m.amount}}</td>
                <td>{{ m.project}}</td>
                <td>{{ m.user}}</td>
                <td>{{ m.create_date}}</td>



            </tr>
            {% endfor %}
            </table>
            <a href="{% url 'Users:edit' %}">update your information</a>


        </div>
      </div>
    </div>
{% endblock content %}

Users/templates/users/register.html
{% extends "users/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Register</legend>
                {{ form|crispy }}
                {{ profile|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Sign Up</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Already Have An Account? <a class="ml-2" href="{% url 'login' %}">Sign In</a>
            </small>
        </div>
    </div>
{% endblock content %}

Users/templates/users/search.html
{% extends "users/base.html" %}
{% block content %}
    <div class="alert alert-primary text-center" style="font-size:20px" role="alert">
              {{ message }}
                <hr>
            <div class="card-columns">
                {% for project in records %}
                <div class="card">
                    {% for image in project.first_image %}
                    <img class="card-img-top" src="{{ image.image.url }}" alt="Card image cap">
                    {% endfor %}
                    <div class="card-body">
                      <h5 class="card-title">{{ project.title }}</h5>
                      <p class="card-text">{{ project.details }}</p>
                    </div>
                    <div class="card-footer">
                      <small class="text-muted"><a href="{% url 'show_project' project.id %}">See More</a></small>
                    </div>
                  </div>
            {% endfor %}
        </div>
    </div>
{% endblock content %}